spring:
  #security:
    #oauth2:
      #client:
        #registration:
          #google:
            #client-id: 513607975763-ckfoe9j1hc73feh78svnr1jcrlnao4g3.apps.googleusercontent.com
            #client-secret: KZScMyzd0Y7TyjrKqprntdMd
  data:
    mongodb:
      uri: mongodb+srv://ajerds:Dd2-Y5F-wA6-hv2@cluster0-knvni.gcp.mongodb.net/test?retryWrites=true&w=majority
      database: heBREWS
